name: "pnpm install"
description: "Installs dependencies via pnpm"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0

    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        cache: "pnpm"
        node-version-file: ".nvmrc"

    - name: Install via pnpm
      run: pnpm install
      shell: bash
